language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_37c734d3f559_key -iv $encrypted_37c734d3f559_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties
  -d
env:
  global:
    secure: edjm6kbgOmlH8KPc3mGH66eyEiAfili3qpFNh22SwIcS43Mh1+oEMQRf2U2xicrVe/vOpMrEwaaz5Wbc4KvDs6YVLc93Bfovum/D5qOKh0bCQvZA18j4XgG4ppeGBQvTEUw4NQWT3Yk3loj+WGMhZXgQYQB1t4ovNA0W0ue6sKbnwze9WEw+b5wM5jpBW3PY/p43PonxNT+3BKAvcphpD6sypB4WsKG5E0xe1+CIGyS1S+bvVOsJRvwmR6/AdHUB97kMcLZEz3kx4kcNM+1xdYOFhTG/10SWfZevJIDjwZ8S9zaSwywzWSkgHLa4CQj85ExMWYfPMdjpLssl27gA3+DR3YRQhP2YkFEeAq7iKSks8MsVhYHJc15AnhDwIURl9o0WgMzlJWgQZzRZUmGHPa0jm1BvUtN0idfLa4Tr8Y9GwXu5CNtG0bFlH8ZbvJgyiHZJ/Ho170CCRYynCej3/9vGTJ5XqIYv8U/aCdCpvskoQQppczVCmA9xumDC3afNBcWofLKHwPrFZvRRYoygPSxceIuW7OvtO6CtKxuk/tHJ5zPF9zAZVWNnFxI1Z+bYWJvHQibzx8X/qPagVDR8szaUCu7zlpJLIpIY14nXeR3Lbu42jDyUk2c7FjBz+0mpNNP5GztWc/TfiiWJTm7++JEOtuvZm5BPvvf9ZBm+DbI=
